import { Lead } from '@/components/lead-card';

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    name: 'TechFlow Solutions',
    category: 'tech',
    location: 'San Francisco, CA',
    phone: '+1 (415) 555-0101',
    website: 'https://techflow.example.com',
    verified: true,
    score: 92,
    status: 'ready',
    discovered: '2024-04-20',
  },
  {
    id: '2',
    name: 'CloudNine Innovations',
    category: 'saas',
    location: 'San Francisco, CA',
    phone: '+1 (415) 555-0102',
    website: 'https://cloudnine.example.com',
    verified: true,
    score: 88,
    status: 'ready',
    discovered: '2024-04-19',
  },
  {
    id: '3',
    name: 'DataBridge Inc',
    category: 'tech',
    location: 'San Francisco, CA',
    verified: false,
    score: 76,
    status: 'enriching',
    discovered: '2024-04-22',
  },
  {
    id: '4',
    name: 'Golden Gate Retail',
    category: 'retail',
    location: 'San Francisco, CA',
    phone: '+1 (415) 555-0104',
    verified: true,
    score: 71,
    status: 'discovered',
    discovered: '2024-04-22',
  },
  {
    id: '5',
    name: 'FinTech Pioneers',
    category: 'finance',
    location: 'San Francisco, CA',
    website: 'https://fintech-pioneers.example.com',
    verified: true,
    score: 85,
    status: 'ready',
    discovered: '2024-04-18',
  },
  {
    id: '6',
    name: 'HealthHub Services',
    category: 'healthcare',
    location: 'San Francisco, CA',
    phone: '+1 (415) 555-0106',
    website: 'https://healthub.example.com',
    verified: true,
    score: 82,
    status: 'enriching',
    discovered: '2024-04-21',
  },
  {
    id: '7',
    name: 'E-Commerce Plus',
    category: 'ecommerce',
    location: 'San Francisco, CA',
    website: 'https://ecommerce-plus.example.com',
    verified: false,
    score: 68,
    status: 'discovered',
    discovered: '2024-04-22',
  },
  {
    id: '8',
    name: 'Swift Analytics',
    category: 'tech',
    location: 'San Francisco, CA',
    phone: '+1 (415) 555-0108',
    website: 'https://swift-analytics.example.com',
    verified: true,
    score: 89,
    status: 'ready',
    discovered: '2024-04-19',
  },
  {
    id: '9',
    name: 'Creative Minds Agency',
    category: 'retail',
    location: 'San Francisco, CA',
    phone: '+1 (415) 555-0109',
    verified: false,
    score: 61,
    status: 'discovered',
    discovered: '2024-04-22',
  },
  {
    id: '10',
    name: 'SecureFlow Systems',
    category: 'tech',
    location: 'San Francisco, CA',
    website: 'https://secureflow.example.com',
    verified: true,
    score: 93,
    status: 'ready',
    discovered: '2024-04-17',
  },
  {
    id: '11',
    name: 'Market Leaders Inc',
    category: 'finance',
    location: 'San Francisco, CA',
    phone: '+1 (415) 555-0111',
    website: 'https://market-leaders.example.com',
    verified: true,
    score: 79,
    status: 'ready',
    discovered: '2024-04-20',
  },
  {
    id: '12',
    name: 'NextGen Wellness',
    category: 'healthcare',
    location: 'San Francisco, CA',
    verified: false,
    score: 74,
    status: 'enriching',
    discovered: '2024-04-22',
  },
];
